version: '{branch}-{build}'
branches:
  only:
  - master
build: off
deploy: off
clone_depth: 2
cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> appveyor.yml'
install:
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: .\test\bin\init.ps1
test_script:
  - ps: $result = invoke-pester -path test/ -outputfile TestResults.xml -outputformat NUnitXML -passthru; $env:failedcount = $result.failedcount
  - ps: (new-object net.webclient).uploadfile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (resolve-path ./TestResults.xml))
  - ps: if($env:failedcount -gt 0) { exit $env:failedcount }
